version: "3.9"
services:
  user:
    container_name: user
    build: ./user
    ports:
      - 5000:5000
    environment:
      - OTEL_SERVICE_NAME=user-service
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=a8bbcf79-7858-4388-809e-a5dc1b3f29ea
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://otelcol.aspecto.io:4317

  todo:
    container_name: todo
    build: ./todo
    ports:
      - 5001:5000
    environment:
      - OTEL_SERVICE_NAME=todo-service
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=a8bbcf79-7858-4388-809e-a5dc1b3f29ea
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://otelcol.aspecto.io:4317
